### ISSUE TITLE
DevDependencies

### ISSUE THREAD

**Issue by fgiarritiello** [rekit/rekit#138]
Hi, is there a reason why all the packages are installed as dependencies but not as devDepensencies? I I think the babel, loaders, eslint all the test related packages could be installed using --save-dev

**Comment by supnate** [comment]
If you won't publish the project to npm as a library then it doesn't matter whether to use devDependencies or dependencies.

**Comment by jgannaway** [comment]
It would be nice to understand which dependencies are only required for local development and testing (devDependencies) ... especially, with all the audit vulnerabilities that result from a new app created from rekit.  If all the vulnerabilities were for devDependencies, I would still consider using rekit, but since I don't know, I'm leaning towards create-react-app.

**Comment by supnate** [comment]
Rekit is based on create-react-app which just also put all deps in dependencies. Reason is just as I mentioned above:

> If you won't publish the project to npm as a library then it doesn't matter whether to use devDependencies or dependencies.
