### ISSUE TITLE
No tests are found

### ISSUE THREAD

**Issue by dkocich** [rekit/rekit#197]
Hello, thanks for the project.

I might have a issue - it is not possible to run any tests through the Rekit UI or command line. Generated tests existing since the first week of my work on the project.

Might it be caused by the fact that the project is initialized in a subfolder in amonorepo?

Thanks for any advice.

![chrome_2019-05-07_07-21-00](https://user-images.githubusercontent.com/6165660/57287606-2c3d0280-70b8-11e9-8893-37bf5bb0f910.png)

**Comment by supnate** [comment]
Hi @dkocich , thanks for reporting this!
Maybe it's really related with subfolder, does it work on a separate folder?

Btw, if you start a new project, I suggest you can use 3.0 beta which has a different testing view.
```
> npm install rekit@next rekit-studio@next
> rekit create app1
> cd app1
> npm install
> rekit-studio
```
Now rekit-studio is a global module to start IDE rather than a dependency of your project.

**Comment by TeresaZhang7517** [comment]
@supnate Hi, I got same issue when I click run all tests in rekit-studio. And I use rekit init project.
![image](https://user-images.githubusercontent.com/36947669/111255040-469b7c00-8651-11eb-9471-5a989c66db7c.png)
